### ISSUE TITLE
RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by simplesaad** [keyurr2/virtual-try-on#1]
I have placed open shape_predictor_68_face_landmarks.dat in the project file. How do I resolve it?

![image](https://user-images.githubusercontent.com/29461284/55617680-4c745b80-57b2-11e9-9162-33f9fed9cbe8.png)

**Comment by dinusha94** [comment]
I had the same problem,It was resolve by adding the path string in the code as just the name of the "your shape predictor.dat", For this to work your code file and "shape predictor .dat" file should be in the same folder .

**Comment by keyurr2** [comment]
@simplesaad Please refer the @dinusha94 answer.
